### ISSUE TITLE
Where i can find example of cascade effect?

### ISSUE THREAD

**Issue by SPAHI4** [steadicat/react-rebound#1]

**Comment by steadicat** [comment]
Good question. I haven’t built this yet. I imagine you could use a timer to trigger an animation for each of your elements at different times.

I could add a `delay` parameter to defer the animation by a certain amount of time. That should make it easier. Would this work for you?

``` js
  {items.map((item, i) =>
    <Animate translateX={visible ? 0 : -100} delay={i * 10} />
  )}
```

**Comment by steadicat** [comment]
@SPAHI4, I added a `delay` option and I also made a few examples for you. You can see them [here](http://steadicat.github.io/react-rebound/). The source code for those demos is [here](https://github.com/steadicat/react-rebound/blob/master/demo.js). Hope this works for you!

**Comment by SPAHI4** [comment]
Great job! Many thanks 👍
