### ISSUE TITLE
<Animate> and ref={} not working

### ISSUE THREAD

**Issue by 3xpedia** [steadicat/react-rebound#8]
Hello, using ref={} do not return a ref when the component is nested inside an <Animate> tag
See : 
`const Menu = () => {
    let menu = useRef();
    const [hover, setHover] = useState(false);

    useEffect(() => {
        if(menu) {
            console.log(menu.current)
        }
    })

    return (
        <Animate translateX={hover ? -100 : 0}>
            <div
                style={{width: '200px', height: '100vh', backgroundColor: settings.colors.primary}}
                onMouseEnter={() => setHover(true)}
                onMouseLeave={() => setHover(false)}
                ref={menu}>
                <p>
                    Hello
                </p>
            </div>
        </Animate>
    )
}`
The value of menu.current is always undefined.
This issue occurs while using functionnal compoennts (not tested on class component).
We can solve it using the useAnimation hook

**Comment by steadicat** [comment]
Yes this is a known downside of the current `Animate` API. I do not believe there is a way, in recent versions of React, for `Animate` to use a `ref` and also pass it through to the owner component. This used to be possible when refs were functions, but no longer. I suggest using the `useAnimation` hook in this case.

**Comment by steadicat** [comment]
I implemented a hacky version of `ref` forwarding in `0.8.3`. Please give it a try.
